<!DOCTYPE html>
<html>
	<head>
		<title>Website Update | <?= htmlspecialchars($title) ?></title>
		<link rel="shortcut icon" href="<?= $base_url ?>img/favicon.ico">
		<link rel="icon" href="<?= $base_url ?>img/favicon.png">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="<?= $base_url ?>css/sweetalert.css">
		<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
		<script src="<?= $base_url ?>js/sweetalert.min.js"></script>
		<style>
            html *:not(h2){
                font-family: "Calibri Light";
				font-size: 14px !important;
			}
			h2{
                font-weight: 600;
			}
		</style>
	</head>

	<body >
		<div class="container" style="min-height: 90vh;">
			<div class="col-md-offset-4 col-md-4" style="margin-top: 70px;">
				<div class="row">
					<div style="text-align: center;">
						<img src="<?= $base_url ?>img/logo.png" style=" max-height: 300px; max-width: 300px; height: auto; width: auto;" alt="Logo">
					</div>
					<div class="form-group">
						<label for="upload_link">Package File</label>
						<input type="file" class="form-control" id="upload_link" placeholder="Select package file to upload" name="zip_file">
						<input type="hidden" id="file_size" value="<?= $file_size_limit ?>"/>
					</div>
				</div>
				<div class="row">
					<div class="progress">
						<div class="progress-bar progress-bar-striped active" role="progressbar" id="progress_bar"
							 aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width:0%">
						</div>
					</div>
				</div>
				<div class="row">
					<div class="form-group">
						<input id="Complete" class="btn btn-primary" value="Update" type="button"/>
                        <a href="<?= $base_url ?>" class="btn btn-success" >Back to Application</a>
					</div>
				</div>
			</div>
		</div>
        <div style=" min-height: 100px; border-top: #265a88 2px solid; max-width: 100%">
            <div class="container">
                <small style="float: right"> Version: <?= $app_version ?></small>
                <br>
                <small style="float: right"> Framework: <?= $framework_version ?></small>
            </div>
        </div>
        <style>
				.form-control{
                    color: inherit !important;
				}
        </style>

        <script>
            $(document).ready(function () {
                $("#Complete").click(function(e) {
                    e.preventDefault();
                    $('#Complete').button('loading');
                    var errors = false;
                    var error_message = '';
                    var file_data = new FormData();
                    var file = $('#upload_link');
                    var max_file_size = $('#file_size');
                    var progress_bar = $('#progress_bar');

                    if(file.length){
                        $(file).each(function(e){
                            var fl = file[e].files[0];
                            if(fl){
                                if(fl.size > max_file_size.val()){
                                    errors = true;
                                    error_message = 'file uploaded exceeds maximum size allowed';
                                }
                                else{
                                    file_data.append(file[e].name,fl);
                                }
                            }
                            else{
                                errors = true;
                                error_message = 'No package file detected';
                            }
                        });
                    }

                    if(!errors){
                        progress_bar.css('width','16%');
                        progress_bar.css('background-color','#337ab7');
                        progress_bar.text('16% (Uploading package)');

                        $.ajax({
                            url				:'/update',
                            type 			: 'post',
                            processData		: false,
                            contentType		: false,
                            mimeType		: 'multipart/form-data',
                            data			: file_data,
                            success			: () => {
                                bootstrap();
                            },
                            error: function(xhr, status, error){
                                $('#Complete').button('reset');
                                progress_bar.css('width','100%');
                                progress_bar.css('background-color','#d61515');
                                progress_bar.text('Update Failed! ('+error+')');
                                $('#upload_link').val('');
                            }
                        });
                    }
                    else{
                        $('#Complete').button('reset');
                        progress_bar.css('width','100%');
                        progress_bar.css('background-color','#d61515');
                        progress_bar.text('Update Failed! ('+error_message+')');
                        $('#upload_link').val('');
                    }
                    return false;
                });
            });

            function bootstrap(){
                var progress_bar = $('#progress_bar');
                progress_bar.css('background-color','#337ab7');
                progress_bar.css('width','32%');
                progress_bar.text('32% (getting your package Ready.....)');
                $.post('/update/bootstrap-update',{dummy:'text'},() => {
                    extract();
                }).fail((xhr, status, error) => {
                    $('#Complete').button('reset');
                    progress_bar.css('width','100%');
                    progress_bar.css('background-color','#d61515');
                    progress_bar.text('Update Failed! ('+error+')');
                    $('#upload_link').val('');
                });
            }

            function extract(){
                var progress_bar = $('#progress_bar');
                progress_bar.css('background-color','#337ab7');
                progress_bar.css('width','48%');
                progress_bar.text('48% (extracting package information.....)');
                $.post('/update/extract-update',{dummy:'text'},() => {
                    backup();
                }).fail((xhr, status, error) => {
                    $('#Complete').button('reset');
                    progress_bar.css('width','100%');
                    progress_bar.css('background-color','#d61515');
                    progress_bar.text('Update Failed! ('+error+')');
                    $('#upload_link').val('');
                });
            }

            function backup(){
                var progress_bar = $('#progress_bar');
                progress_bar.css('background-color','#337ab7');
                progress_bar.css('width','64%');
                progress_bar.text('64% (backing up files.....)');
                $.post('/update/backup-update',{dummy:'text'},() => {
                    execute();
                }).fail((xhr, status, error) => {
                    $('#Complete').button('reset');
                    progress_bar.css('width','100%');
                    progress_bar.css('background-color','#d61515');
                    progress_bar.text('Update Failed! ('+error+')');
                    $('#upload_link').val('');
                });
            }

            function execute(){
                var progress_bar = $('#progress_bar');
                progress_bar.css('background-color','#337ab7');
                progress_bar.css('width','80%');
                progress_bar.text('80% (applying package. please wait...)');
                $.post('/update/execute-update',{dummy:'text'},() => {
                    cleanup();
                }).fail((xhr, status, error) => {
                    $('#Complete').button('reset');
                    progress_bar.css('width','100%');
                    progress_bar.css('background-color','#d61515');
                    progress_bar.text('Update Failed! ('+error+')');
                    $('#upload_link').val('');
                });
            }

            function cleanup(){
                var progress_bar = $('#progress_bar');
                progress_bar.css('background-color','#337ab7');
                progress_bar.css('width','96%');
                progress_bar.text('96% (package applied! cleaning up.....)');
                $.post('/update/cleanup-update',{dummy:'text'},() =>{
                    progress_bar.css('width','100%');
                    progress_bar.text('100% Update Complete!');
                    $('#Complete').button('reset');
                    $('#upload_link').val('');
                }).fail((xhr, status, error) => {
                    $('#Complete').button('reset');
                    progress_bar.css('width','100%');
                    progress_bar.css('background-color','#d61515');
                    progress_bar.text('Update Failed! ('+error+')');
                    $('#upload_link').val('');
                });
            }
        </script>
	</body>
